### ISSUE TITLE
ShopifyNavigationComponent undefined method after updating gem 2.82.0 to 3.0.0

### ISSUE THREAD

**Issue by kgorshkov** [baoagency/polaris_view_components#291]
ShopifyNavigationComponent undefined method 'link' for after updating gem 2.82.0 to 3.0.0

ruby 3.2.1
rails 7.0.4.3
hotwire-livereload 1.2.3

After seeing the error after updating the gem, I did try running the installer:

> rails polaris_view_components:install

...but the error remains.  I encountered this both on Windows 11 localhost and also deployed to Heroku Linux.

Usage of polaris_shopify_navigation is standard just as [example](https://polarisviewcomponents.org/lookbook/inspect/shopify_navigation/with_auto_detection)

> 2023-04-24T17:52:19.017623+00:00 app[web.1]: [fdc4d191-ef1e-47db-9651-26389131be16] ActionView::Template::Error (undefined method `link' for #<Polaris::ShopifyNavigationComponent:0x00007f0e6b67a1f8 @auto_detect_active=true, @system_arguments={:tag=>"div", :classes=>"shp-Navigation"}, @view_context=#<ActionView::Base:0x0000000002aa08>, @__vc_original_view_context=#<ActionView::Base:0x0000000002aa08>, @output_buffer="", @lookup_context=#<ActionView::LookupContext:0x00007f0e6b5b30d0 @details_key=#<ActionView::TemplateDetails::Requested:0x00007f0e6b67f3d8 @locale=[:en], @handlers=[:raw, :erb, :html, :builder, :ruby], @formats=[:html], @variants=[], @locale_idx={:en=>0, nil=>1}, @handlers_idx={:raw=>0, :erb=>1, :html=>2, :builder=>3, :ruby=>4, nil=>5}, @formats_idx={:html=>0, nil=>1}, @variants_idx={nil=>0}>, @digest_cache=nil, @cache=true, @prefixes=["home", "authenticated", "application"], @details={:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}, @view_paths=#<ActionView::PathSet:0x00007f0e6b5c2dc8 @paths=[#<ActionView::FileSystemResolver:0x00007f0e6bf545d0 @unbound_templates=#<Concurrent::Map:0x00007f0e6bf545a8 entries=3 default_proc=nil>, @path_parser=#<ActionView::Resolver::PathParser:0x00007f0e6c74eb00 @regex=/
2023-04-24T17:52:19.017624+00:00 app[web.1]:           \A
2023-04-24T17:52:19.017625+00:00 app[web.1]:           (?:(?<prefix>.*)\/)?
2023-04-24T17:52:19.017625+00:00 app[web.1]:           (?<partial>_)?
2023-04-24T17:52:19.017625+00:00 app[web.1]:           (?<action>.*?)
2023-04-24T17:52:19.017626+00:00 app[web.1]:           (?:\.(?<locale>[a-z]{2}(?:[-_][A-Z]{2})?))??
2023-04-24T17:52:19.017627+00:00 app[web.1]:           (?:\.(?<format>html|text|js|css|ics|csv|vcf|vtt|png|jpeg|gif|bmp|tiff|svg|mpeg|mp3|ogg|m4a|webm|mp4|otf|ttf|woff|woff2|xml|rss|atom|yaml|multipart_form|url_encoded_form|json|pdf|zip|gzip|turbo_stream))??
2023-04-24T17:52:19.017628+00:00 app[web.1]:           (?:\+(?<variant>[^.]*))??
2023-04-24T17:52:19.017628+00:00 app[web.1]:           (?:\.(?<handler>raw|erb|html|builder|ruby))?
2023-04-24T17:52:19.017628+00:00 app[web.1]:           \z
2023-04-24T17:52:19.017635+00:00 app[web.1]:         /x>, @path="/app/app/views">, #<ActionView::FileSystemResolver:0x00007f0e6bf54738 @unbound_templates=#<Concurrent::Map:0x00007f0e6bf54710 entries=0 default_proc=nil>, @path_parser=#<ActionView::Resolver::PathParser:0x00007f0e6c74e948>, @path="/app/vendor/bundle/ruby/3.2.0/gems/hotwire-livereload-1.2.3/app/views">, #<ActionView::FileSystemResolver:0x00007f0e6bf548a0 @unbound_templates=#<Concurrent::Map:0x00007f0e6bf54878 entries=0 default_proc=nil>, @path_parser=#<ActionView::Resolver::PathParser:0x00007f0e6c74e920>, @path="/app/vendor/bundle/ruby/3.2.0/gems/turbo-rails-1.4.0/app/views">, #<ActionView::FileSystemResolver:0x00007f0e6bf54a08 @unbound_templates=#<Concurrent::Map:0x00007f0e6bf549e0 entries=0 default_proc=nil>, @path_parser=#<ActionView::Resolver::PathParser:0x00007f0e6c74e808>, @path="/app/vendor/bundle/ruby/3.2.0/gems/view_component-3.0.0/app/views">, #<ActionView::FileSystemResolver:0x00007f0e6bf54b70 @unbound_templates=#<Concurrent::Map:0x00007f0e6bf54b48 entries=0 default_proc=nil>, @path_parser=#<ActionView::Resolver::PathParser:0x00007f0e6c74e6c8>, @path="/app/vendor/bundle/ruby/3.2.0/gems/shopify_app-21.4.1/app/views">, #<ActionView::FileSystemResolver:0x00007f0e6bf54d28 @unbound_templates=#<Concurrent::Map:0x00007f0e6bf54d00 entries=0 default_proc=nil>, @path_parser=#<ActionView::Resolver::PathParser:0x00007f0e6c74e5b0>, @path="/app/vendor/bundle/ruby/3.2.0/gems/actiontext-7.0.4.3/app/views">, #<ActionView::FileSystemResolver:0x00007f0e6bf55098 @unbound_templates=#<Concurrent::Map:0x00007f0e6bf54ff8 entries=0 default_proc=nil>, @path_parser=#<ActionView::Resolver::PathParser:0x00007f0e6c74e498>, @path="/app/vendor/bundle/ruby/3.2.0/gems/actionmailbox-7.0.4.3/app/views">]>>, @view_renderer=#<ActionView::Renderer:0x00007f0e69aadad8 @lookup_context=#<ActionView::LookupContext:0x00007f0e6b5b30d0 @details_key=#<ActionView::TemplateDetails::Requested:0x00007f0e6b67f3d8 @locale=[:en], @handlers=[:raw, :erb, :html, :builder, :ruby], @formats=[:html], @variants=[], @locale_idx={:en=>0, nil=>1}, @handlers_idx={:raw=>0, :erb=>1, :html=>2, :builder=>3, :ruby=>4, nil=>5}, @formats_idx={:html=>0, nil=>1}, @variants_idx={nil=>0}>, @digest_cache=nil, @cache=true, @prefixes=["home", "authenticated", "application"], @details={:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}, @view_paths=#<ActionView::PathSet:0x00007f0e6b5c2dc8 @paths=[#<ActionView::FileSystemResolver:0x00007f0e6bf545d0 @unbound_templates=#<Concurrent::Map:0x00007f0e6bf545a8 entries=3 default_proc=nil>, @path_parser=#<ActionView::Resolver::PathParser:0x00007f0e6c74eb00 @regex=/
2023-04-24T17:52:19.017636+00:00 app[web.1]:           \A
2023-04-24T17:52:19.017636+00:00 app[web.1]:           (?:(?<prefix>.*)\/)?
2023-04-24T17:52:19.017636+00:00 app[web.1]:           (?<partial>_)?
2023-04-24T17:52:19.017636+00:00 app[web.1]:           (?<action>.*?)
2023-04-24T17:52:19.017637+00:00 app[web.1]:           (?:\.(?<locale>[a-z]{2}(?:[-_][A-Z]{2})?))??
2023-04-24T17:52:19.017637+00:00 app[web.1]:           (?:\.(?<format>html|text|js|css|ics|csv|vcf|vtt|png|jpeg|gif|bmp|tiff|svg|mpeg|mp3|ogg|m4a|webm|mp4|otf|ttf|woff|woff2|xml|rss|atom|yaml|multipart_form|url_encoded_form|json|pdf|zip|gzip|turbo_stream))??
2023-04-24T17:52:19.017637+00:00 app[web.1]:           (?:\+(?<variant>[^.]*))??
2023-04-24T17:52:19.017638+00:00 app[web.1]:           (?:\.(?<handler>raw|erb|html|builder|ruby))?
2023-04-24T17:52:19.017638+00:00 app[web.1]:           \z
2023-04-24T17:52:19.017641+00:00 app[web.1]:         /x>, @path="/app/app/views">, #<ActionView::FileSystemResolver:0x00007f0e6bf54738 @unbound_templates=#<Concurrent::Map:0x00007f0e6bf54710 entries=0 default_proc=nil>, @path_parser=#<ActionView::Resolver::PathParser:0x00007f0e6c74e948>, @path="/app/vendor/bundle/ruby/3.2.0/gems/hotwire-livereload-1.2.3/app/views">, #<ActionView::FileSystemResolver:0x00007f0e6bf548a0 @unbound_templates=#<Concurrent::Map:0x00007f0e6bf54878 entries=0 default_proc=nil>, @path_parser=#<ActionView::Resolver::PathParser:0x00007f0e6c74e920>, @path="/app/vendor/bundle/ruby/3.2.0/gems/turbo-rails-1.4.0/app/views">, #<ActionView::FileSystemResolver:0x00007f0e6bf54a08 @unbound_templates=#<Concurrent::Map:0x00007f0e6bf549e0 entries=0 default_proc=nil>, @path_parser=#<ActionView::Resolver::PathParser:0x00007f0e6c74e808>, @path="/app/vendor/bundle/ruby/3.2.0/gems/view_component-3.0.0/app/views">, #<ActionView::FileSystemResolver:0x00007f0e6bf54b70 @unbound_templates=#<Concurrent::Map:0x00007f0e6bf54b48 entries=0 default_proc=nil>, @path_parser=#<ActionView::Resolver::PathParser:0x00007f0e6c74e6c8>, @path="/app/vendor/bundle/ruby/3.2.0/gems/shopify_app-21.4.1/app/views">, #<ActionView::FileSystemResolver:0x00007f0e6bf54d28 @unbound_templates=#<Concurrent::Map:0x00007f0e6bf54d00 entries=0 default_proc=nil>, @path_parser=#<ActionView::Resolver::PathParser:0x00007f0e6c74e5b0>, @path="/app/vendor/bundle/ruby/3.2.0/gems/actiontext-7.0.4.3/app/views">, #<ActionView::FileSystemResolver:0x00007f0e6bf55098 @unbound_templates=#<Concurrent::Map:0x00007f0e6bf54ff8 entries=0 default_proc=nil>, @path_parser=#<ActionView::Resolver::PathParser:0x00007f0e6c74e498>, @path="/app/vendor/bundle/ruby/3.2.0/gems/actionmailbox-7.0.4.3/app/views">]>>>, @view_flow=#<ActionView::OutputFlow:0x00007f0e69aad830 @content={}>, @virtual_path="/polaris/shopify_navigation_component", @__vc_variant=nil, @current_template=nil, @__vc_content_evaluated=true, @__vc_render_in_block=#<Proc:0x00007f0e69aa3498 /app/app/views/application/_navigation.html.erb:1>>):
2023-04-24T17:52:19.017642+00:00 app[web.1]: [fdc4d191-ef1e-47db-9651-26389131be16]     1: <%= polaris_shopify_navigation(auto_detect_active: true) do |nav| %>
2023-04-24T17:52:19.017642+00:00 app[web.1]: [fdc4d191-ef1e-47db-9651-26389131be16]     2:   <% nav.link(url: "/home?shop=" + @shop_origin) { "Link Name" } %>
2023-04-24T17:52:19.017643+00:00 app[web.1]: [fdc4d191-ef1e-47db-9651-26389131be16]   
2023-04-24T17:52:19.017644+00:00 app[web.1]: [fdc4d191-ef1e-47db-9651-26389131be16] app/views/application/_navigation.html.erb:2
2023-04-24T17:52:19.017644+00:00 app[web.1]: [fdc4d191-ef1e-47db-9651-26389131be16] app/views/application/_navigation.html.erb:1
2023-04-24T17:52:19.017644+00:00 app[web.1]: [fdc4d191-ef1e-47db-9651-26389131be16] app/views/home/index.html.erb:1
2023-04-24T17:52:19.017645+00:00 app[web.1]: [fdc4d191-ef1e-47db-9651-26389131be16] app/middleware/app_bridge_middleware.rb:23:in `call'

**Comment by resistorsoftware** [comment]
What gem? I have this error too! WTF happened? 2.82 is what gem?

**Comment by kirillplatonov** [comment]
Yeah, the issue is caused by ViewComponents 3 release a few days ago. I'm preparing the patch to lock this gem on 2.x until we upgrade it.

**Comment by kirillplatonov** [comment]
Published v0.13.5 with the hotfix.
